#' Generate data for R Shiny app and for making figures
#'
#' This function calculate the annual values for each indicator and generate the files or data needed to update the figures
#' from Isabel et al. (2025) or to update the figures in the Shiny app.
#'
#'
#' @param data.directory Directory where the nGSL datasets are located. `NGSL_Set.csv`, `NGSL_Capt.csv` and `NGSL_CBio.csv` are needed.
#' @param repository Repository folder where files generated by the function are stored.
#' @param overwrite \code{TRUE} to overwrite existing files.
#'
#' @return (invisible) Files created and stored.
#'
#' @examples
#' # example code
#' generate_data(data.directory = "//dcqcimlna01a//BD_Peches//Releves_Poissons_de_Fond_et_Crevette//Donnees_PACES//", repository = "data/", overwrite = TRUE)
#'
#' @import dplyr
#' @import tidyr
#' @export
generate_data <- function(
    data.directory = data.directory,
    repository = repository,
    overwrite = FALSE
    ) {


  # Create repository if it doesn't exist
  if (!dir.exists(repository)) {
    dir.create(repository, recursive = TRUE, showWarnings = FALSE)
    message("The repository was created.")
  }


  # LOAD DATA ==================================================================
  set <- read.csv(paste0(data.directory, "/NGSL_Set.csv"), sep = ";", na.strings = ". ")
  names(set) <- tolower(names(set))
  names(set) <- recode(names(set), "nbpc" = "nav", "no_rel" = "rel", "no_stn" = "trait")

  catch <- read.csv(paste0(data.directory, "/NGSL_Capt.csv"), sep = ";", na.strings = ". ")
  names(catch) <- tolower(names(catch))
  names(catch) <- recode(names(catch), "nbpc" = "nav", "no_rel" = "rel", "no_stn" = "trait")

  carbio <- read.csv(paste0(data.directory, "/NGSL_CBio.csv"), sep = ";", na.strings = ". ")
  names(carbio) <- tolower(names(carbio))
  names(carbio) <- recode(names(carbio), "nbpc" = "nav", "no_rel" = "rel", "no_stn" = "trait")

  # PREPARE DATA ===============================================================
  cle <- c("nav", "rel", "trait")
  catch <- left_join(catch, set %>% select(all_of(c(cle, "annee", "no_str"))), by = cle)
  catch <- catch %>% filter(annee >= 2006)
  set <- set %>% filter(annee >= 2006)

  # Strata
  core <- c(402,403,405,406,408:410,801,803:807,812:818,822:824,828:833,836,837,839,841)
  core_cv <- c(402, 405, 406, 408, 409, 801, 803:807, 812:818, 822, 823, 828, 830, 832, 836)

  # Select taxa based on filter made by me and PMSC for functional matrix.
  catch <- left_join(catch, taxa %>% select(espece, action, groups), by = "espece")
  cle <- c("nav", "rel", "trait")
  catch <- catch %>% filter(action != 1) %>%
    group_by_at(c(cle, "groups", "categ")) %>%
    mutate(pds_capt_cor_ca = sum(pds_capt_cor_ca),
           nb_capt_cor_ca = sum(nb_capt_cor_ca),
           espece = groups) %>% distinct_at(c(cle, "espece", "categ"), .keep_all = TRUE) %>% as.data.frame()

  catch$groups <- NULL
  catch$action <- NULL

  catch$espece <- as.integer(catch$espece)
  catch$annee <- as.integer(catch$annee)

  set <- set %>% filter(!(annee == 2018 & trait == 131)) # no_str doesn't fit with geographic coordinates
  catch <- catch %>% filter(!(nav == 39 & rel == 15 & trait == 131)) # no_str doesn't fit with geographic coordinates


  output <- import.paces.f(data.directory = data.directory)
  ngsl.comm.data <- output[["ngsl.comm.data"]]
  ngsl.comm.data <- ngsl.comm.data %>% filter(year >= 2006)

  # CALCULATE PUE ==============================================================
  ## All taxa SEPARATED for all nGSL
  dat_tot <- data.frame()
  sp <- unique(catch$espece)
  for (k in sp){
    data <- catch %>% filter(espece == k)
    ans <- c(min(data$annee): max(data$annee))
    pue <- get_pop_indices(ans, set, catch = data, stratum, strates_sel = core, compa.year.meth = 3)
    pue$espece <- k
    dat_tot <- bind_rows(dat_tot, pue)
  }
  dat_tot$PID <- 25

  ## All taxa SEPARATED for each ecosystem region
  dat <- data.frame()
  sp <- unique(catch$espece)
  for (j in sp){
    data <- catch %>% filter(espece == j)
    ans <- c(min(data$annee): max(data$annee))
    pue <- get_pop_indices_RECO(ans, set, catch = data, stratum, strates_sel = core, prop, compa.year.meth = 3)
    pue$espece <- j
    dat <- bind_rows(dat, pue)
  }
  dat <- bind_rows(dat, dat_tot)

  ## All taxa COMBINED WITH redfish for all nGSL
  data <- catch
  ans <- c(min(data$annee): max(data$annee))
  dat_cv <- get_pop_indices(ans, set, catch = data, stratum, strates_sel = core_cv, compa.year.meth = 3)

  ## All taxa COMBINED WITHOUT redfish for all NGSL
  data <- catch %>% filter(espece != 792)
  ans <- c(min(data$annee): max(data$annee))
  dat_cv_sans_seb <- get_pop_indices(ans, set, catch = data, stratum, strates_sel = core_cv, compa.year.meth = 3)

  # Set time series min and max
  min <- min(dat$annee)
  max <- max(dat$annee)



  # PRODUCTIVITY ===============================================================
  dat_prod <- dat
  dat_prod$gr <- ifelse(dat_prod$espece == 792, "Sébastes", ifelse(dat_prod$espece == 8111, "Crevette nordique", "Autres espèces"))
  dat_prod$PID <- as.integer(dat_prod$PID)

  ### Fishes anomalies ---
  dat_prod1 <- dat_prod %>% filter(espece < 1000) %>% group_by(annee, PID, gr) %>% summarise(pds_tot = sum(pds_mean)) %>% as.data.frame()
  serie <- dat_prod1 %>% filter(annee != max) %>% # exclude last year of the series
    group_by(PID, gr) %>%
    summarise(pds_serie = mean(pds_tot),
              sd = sd(pds_tot)) %>%
    as.data.frame()
  dat_prod1 <- left_join(dat_prod1, serie, by = c("PID", "gr"))
  dat_prod1 <- dat_prod1 %>% group_by(PID, annee, gr) %>%
    reframe(anom = (pds_tot - pds_serie) / sd, mean = pds_tot) %>% distinct()

  ## Invertebrates anomalies ---
  dat_prod2 <- dat_prod %>% filter(espece > 1000) %>% group_by(annee, PID, gr) %>% summarise(pds_tot = sum(pds_mean)) %>% as.data.frame()
  serie <- dat_prod2 %>% filter(annee != max) %>% # exclude last year of the series
    group_by(PID, gr) %>%
    summarise(pds_serie = mean(pds_tot),
              sd = sd(pds_tot)) %>%
    as.data.frame()
  dat_prod2 <- left_join(dat_prod2, serie, by = c("PID", "gr"))
  dat_prod2 <- dat_prod2 %>% group_by(PID, annee, gr) %>%
    summarise(anom = (pds_tot - pds_serie) / sd, mean = pds_tot) %>% distinct()

  dat_prod1[dat_prod1$gr == "Autres espèces", ]$gr <- "Autres poissons"
  dat_prod2[dat_prod2$gr == "Autres espèces", ]$gr <- "Autres invertébrés"

  dat_productivity <- bind_rows(dat_prod1, dat_prod2)
  dat_productivity$Box <- ifelse(dat_productivity$PID == 1, "Nord-ouest du golfe",
                                 ifelse(dat_productivity$PID == 2, "Nord-est du golfe",
                                        ifelse(dat_productivity$PID == 3, "Centre du golfe", "nGSL")))
  dat_productivity <- as.data.frame(dat_productivity)


  # STABILITY ==================================================================
  moving_average <- function(x, n) {
    stats::filter(x, rep(1/n, n), sides = 1) }

  ## WITH redfish
  dat_CV1 <- dat_cv %>% mutate(cv = sd_p/pds_mean)
  cv_values <- moving_average(dat_CV1$cv, 3)
  dat_CV1 <- data.frame(YEAR = min:max, cv_tot = cv_values)
  dat_CV1 <- dat_CV1 %>% mutate(cv_tot = 1/cv_tot) # Inverse CV

  ## WITHOUT redfish
  dat_CV2 <- dat_cv_sans_seb %>% mutate(cv = sd_p/pds_mean)
  cv_values <- moving_average(dat_CV2$cv, 3)
  dat_CV2 <- data.frame(YEAR = min:max, cv_sans_seb = cv_values)
  dat_CV2 <- dat_CV2 %>% mutate(cv_sans_seb = 1/cv_sans_seb) # Inverse CV

  dat_CV <- left_join(dat_CV1, dat_CV2, by = c("YEAR")) # combine 1/CV with and without redfish for figure

  names(dat_CV) <- recode(names(dat_CV), "YEAR" = "annee")
  dat_stability <- as.data.frame(dat_CV)


  # CLIMATE CHANGE =============================================================
  ## THERMIC GUILDS
  dat_thermic <- dat %>% filter(PID == 25) # 25 = all nGSL
  f <- c(451, 728, 847, 8075, 8077, 8138)
  h <- c(27, 193, 449, 8113, 8135, 4753)
  dat_thermic$group <- ifelse(dat_thermic$espece %in% f, "froid", ifelse(dat_thermic$espece %in% h, "chaud", NA))
  dat_thermic$annee <- as.integer(dat_thermic$annee)

  ## Warm guild ---
  dat_thermic_h <- dat_thermic %>% filter(group == "chaud")

  serie <- dat_thermic_h %>% filter(annee!= max) %>%
    group_by(espece) %>%
    summarise(pds_serie = mean(pds_mean),
              sd = sd(pds_mean))
  dat_thermic_h <- left_join(dat_thermic_h, serie, by = "espece")

  dat_thermic_h <- dat_thermic_h %>% group_by(annee, espece) %>%
    summarise(pds = (pds_mean - pds_serie) / sd) %>%
    distinct() %>% as.data.frame()
  dat_thermic_h$annee <- as.character(dat_thermic_h$annee)

  ## Cold guild ---
  dat_thermic_c <- dat_thermic %>% filter(group == "froid")

  serie <- dat_thermic_c %>% filter(annee != max) %>%
    group_by(espece) %>%
    summarise(pds_serie = mean(pds_mean),
              sd = sd(pds_mean))
  dat_thermic_c <- left_join(dat_thermic_c, serie, by = "espece")

  dat_thermic_c <- dat_thermic_c %>% group_by(annee, espece) %>%
    summarise(pds = ((mean(pds_mean)) - pds_serie) / sd) %>%
    distinct() %>% as.data.frame()
  dat_thermic_c$annee <- as.character(dat_thermic_c$annee)

  ## Add taxonomic names for figure
  dat_thermic_h <- left_join(dat_thermic_h, taxa %>% select(espece, nom_commun_fr, nom_commun_en), by = "espece")
  dat_thermic_c <- left_join(dat_thermic_c, taxa %>% select(espece, nom_commun_fr, nom_commun_en), by = "espece")

  dat_thermic_h$guild <- "chaud"
  dat_thermic_c$guild <- "froid"
  dat_climate_guild <- bind_rows(dat_thermic_h, dat_thermic_c)

  ## CTI
  names(tol) <- recode(names(tol), "species" = "espece", "year" = "annee")

  dat_cti <- left_join(dat, tol %>% select(espece, annee, p2), by = c("espece", "annee"))
  dat_cti$p2 <- as.numeric(dat_cti$p2) # p2 is 50th percentile
  dat_thermal <- dat_cti %>% filter(!is.na(p2)) %>%
    group_by(espece) %>%
    arrange(espece) %>%
    summarise(tmp_MP = median(p2)) %>% distinct()
  spp <- unique(dat_thermal$espece)

  # Calculate CTI for each ecosystem region
  PID <- unique(dat$PID)
  dat_cti_PID <- data.frame()
  for (i in PID){
    dat_PID <- dat_cti %>% filter(PID == i)
    dat_abund <- dat_PID %>% filter(espece %in% spp) %>%
      arrange(espece) %>%
      select(espece, annee, pds_mean) %>%
      pivot_wider(names_from = "annee", values_from = "pds_mean", values_fill = 0) %>%
      select(-espece)
    cti <- colSums(log10(dat_abund+1)*dat_thermal$tmp_MP) / colSums(log10(dat_abund+1))
    cti <- as.data.frame(cti)
    cti$annee <- as.numeric(row.names(cti))
    names(cti) <- c("cti", "annee")
    cti$PID <- i
    dat_cti_PID <- bind_rows(dat_cti_PID, cti)
  }

  dat_cti_PID$Box <- ifelse(dat_cti_PID$PID == 1, "Nord-ouest du golfe",
                        ifelse(dat_cti_PID$PID == 2, "Nord-est du golfe",
                               ifelse(dat_cti_PID$PID == 3, "Centre du golfe", "nGSL")))
  dat_climate_cti <- as.data.frame(dat_cti_PID)


  # ENERGY FLUX ================================================================
  names(mat) <- recode(names(mat), "STRAP" = "espece")
  mat <- mat %>% select(espece,PIP,PILD,PB,PP,MM,MD,IF,IB)

  ## BIOMASS OF TROPHIC GUILDS
  dat_flux <- left_join(dat, mat, by = "espece")
  dat_flux1 <- dat_flux %>% mutate(PIP = pds_mean * PIP,
                        PILD = pds_mean * PILD,
                        PB = pds_mean * PB,
                        PP = pds_mean * PP,
                        MM = pds_mean * MM,
                        MD = pds_mean * MD,
                        IF = pds_mean * IF,
                        IB = pds_mean * IB)
  dat_flux1 <- dat_flux1 %>% group_by(annee, PID) %>%
                             summarise(PIP = sum(PIP),
                                      PILD = sum(PILD),
                                      PB = sum(PB),
                                      PP = sum(PP),
                                      MM = sum(MM),
                                      MD = sum(MD),
                                      IF = sum(IF),
                                      IB = sum(IB))
  vars <- c("PIP", "PILD", "PB", "PP", "MM", "MD", "IF", "IB")
  dat_flux1 <- dat_flux1 %>% pivot_longer(vars, names_to = "guild", values_to = "pds_tot") %>% as.data.frame()

  serie <- dat_flux1 %>% filter(annee != max) %>%
    select(guild, PID, pds_tot) %>%
    group_by(guild, PID) %>%
    summarise(pds_serie = mean(pds_tot),
              sd = sd(pds_tot)) %>%
    as.data.frame()
  dat_flux1 <- left_join(dat_flux1, serie, by = c("guild", "PID"))

  dat_flux1 <- dat_flux1 %>% group_by(annee, guild, PID) %>%
    summarise(anom = (pds_tot - pds_serie) / sd) %>% distinct()

  dat_flux1 <- left_join(dat_flux1, name, by = "guild")
  dat_flux1$Box <- ifelse(dat_flux1$PID == 1, "Nord-ouest du golfe",
                     ifelse(dat_flux1$PID == 2, "Nord-est du golfe",
                            ifelse(dat_flux1$PID == 3, "Centre du golfe", "nGSL")))
  dat_flux_guild1 <- as.data.frame(dat_flux1)

  ## RECENT CHANGES
  dat_flux2 <- dat_flux %>% mutate(PIP = pds_mean * PIP,
                                   PILD = pds_mean * PILD,
                                   PB = pds_mean * PB,
                                   PP = pds_mean * PP,
                                   MM = pds_mean * MM,
                                   MD = pds_mean * MD,
                                   IF = pds_mean * IF,
                                   IB = pds_mean * IB)
  dat_flux2$gr <- ifelse(dat_flux2$espece == 792 | dat_flux2$espece == 791, "Sébastes", "Autres espèces")
  dat_flux2 <- dat_flux2 %>% group_by(annee, PID, gr) %>%
                             summarise(PIP = sum(PIP),
                                       PILD = sum(PILD),
                                       PB = sum(PB),
                                       PP = sum(PP),
                                       MM = sum(MM),
                                       MD = sum(MD),
                                       IF = sum(IF),
                                       IB = sum(IB))

  dat_flux2 <- dat_flux2 %>% pivot_longer(vars, names_to = "guild", values_to = "pds_tot") %>% as.data.frame()

  serie <- dat_flux2 %>% filter(annee != max) %>%
    group_by(PID, guild, gr) %>%
    summarise(serie = mean(pds_tot))
  dat_flux2 <- left_join(dat_flux2, serie, by = c("PID", "guild", "gr"))

  dat_flux2 <- dat_flux2 %>% filter(annee >= max-4) %>%
    group_by(PID, guild, gr) %>%
    mutate(m5 = mean(pds_tot)) %>%
    reframe(val = ((m5-serie)/serie)*100) %>%
    distinct()

  dat_flux2 <- left_join(dat_flux2, name, by = "guild")
  dat_flux2 <- dat_flux2 %>% filter(!is.na(val))
  dat_flux2$Box <- ifelse(dat_flux2$PID == 1, "Nord-ouest du golfe",
                          ifelse(dat_flux2$PID == 2, "Nord-est du golfe",
                                 ifelse(dat_flux2$PID == 3, "Centre du golfe", "nGSL")))
  dat_flux_guild2 <- as.data.frame(dat_flux2)

  ## CATCH RATE
  dat_flux3 <- dat_flux %>% mutate(PIP = pds_mean * PIP,
                                   PILD = pds_mean * PILD,
                                   PB = pds_mean * PB,
                                   PP = pds_mean * PP,
                                   MM = pds_mean * MM,
                                   MD = pds_mean * MD,
                                   IF = pds_mean * IF,
                                   IB = pds_mean * IB) %>%
                            group_by(annee, PID) %>%
                            summarise(PIP = sum(PIP),
                                      PILD = sum(PILD),
                                      PB = sum(PB),
                                      PP = sum(PP),
                                      MM = sum(MM),
                                      MD = sum(MD),
                                      IF = sum(IF),
                                      IB = sum(IB))
  vars <- c("PIP", "PILD", "PB", "PP", "MM", "MD", "IF", "IB")
  dat_flux3 <- dat_flux3 %>% pivot_longer(vars, names_to = "guild", values_to = "pds_tot") %>% as.data.frame()

  dat_flux3 <- left_join(dat_flux3, name, by = "guild")
  dat_flux3$Box <- ifelse(dat_flux3$PID == 1, "Nord-ouest du golfe",
                           ifelse(dat_flux3$PID == 2, "Nord-est du golfe",
                                  ifelse(dat_flux3$PID == 3, "Centre du golfe", "nGSL")))
  dat_flux_guild3 <- as.data.frame(dat_flux3)


  # SIZE STRUCTURE =============================================================
  ## SLOPE OF THE SIZE SPECTRUM
  ### With redfish
  LFS <- CLF.f(ngsl.comm.data = ngsl.comm.data)
  LFS.lm <- CLF.lm.fit(LFS, 5, 100)

  lfs <- as.data.frame(LFS.lm[["ab.stats"]])
  gf <- mgcv::gam(lfs$slopes~ s(lfs$year))
  x <- c(min:max)
  y <- mgcv::predict.gam(gf)
  gam1 <- data.frame(x, y)
  names(gam1) <- c("year", "pente")

  ### Without redfish
  comm.data <- ngsl.comm.data # save data with redfish for later
  ngsl.comm.data <- ngsl.comm.data %>% filter(!codeqc %in% c(792))
  LFS2 <- CLF.f(ngsl.comm.data = ngsl.comm.data)
  LFS.lm2 <- CLF.lm.fit(LFS2, 5, 100)

  lfs2 <- as.data.frame(LFS.lm2[["ab.stats"]])
  gf2 <- mgcv::gam(lfs2$slopes~ s(lfs2$year))
  x <- c(min:max)
  y <- mgcv::predict.gam(gf2)
  gam2 <- data.frame(x, y)
  names(gam2) <- c("year", "pente")

  names(lfs) <- recode(names(lfs), "slopes" = "slope")
  lfs <- lfs[, c("year", "slope")]
  names(gam1) <- recode(names(gam1), "pente" = "gam_tot_slope")
  names(gam2) <- recode(names(gam2), "pente" = "gam_no_seb_slope")

  dat_size_slope <- lfs %>% left_join(gam1, by = "year") %>% left_join(gam2, by = "year")
  dat_size_slope <- as.data.frame(dat_size_slope)

  ## ABUNDANCE AND SPECIES RICHNESS BY SIZE CLASS
  dat_size <- comm.data %>% filter(length >= 5 & length <= 100)

  int_long <- c(5, 15, 25, 35, 45, 55, 65, 75, 85, 101); int_long

  dat_size$cl_long <- NA
  dat_size$ordre <- NA

  for (i in 2:length(int_long)){
    cor <- which(with(dat_size, length >= int_long[i-1] & length < int_long[i])) # [x, y[
    dat_size$cl_long[cor] <- paste0("[", int_long[i-1], "-", int_long[i], "[")
    dat_size$ordre[cor] <- i-1
    rm(cor)
  }
  dat_size <- dat_size %>% arrange(ordre) %>% as.data.frame()
  table(dat_size$cl_long, useNA = "always")

  dat_size_abund <- dat_size %>% group_by(year, cl_long, ordre) %>%
                                 summarise(abundance = sum(abundance))

  serie <- dat_size_abund %>% filter(year != max) %>%
                              group_by(cl_long) %>%
                              summarise(pds_serie = mean(abundance),
                                        sd = sd(abundance)) %>%
                         as.data.frame()
  dat_size_abund <- left_join(dat_size_abund, serie, by = c("cl_long"))

  dat_size_abund <- dat_size_abund %>% group_by(year, cl_long) %>%
                                       summarise(anom = ((mean(abundance)) - pds_serie) / sd) %>% distinct()

  # SPECIES RICHNESS BY SIZE CLASS
  spp <- taxa %>% filter(action != 1) %>% pull(espece)
  dat_size_div <- dat_size %>% filter(codeqc %in% spp) %>%
                               group_by(year, codeqc, english, length, cl_long, ordre) %>%
                               reframe(abundance = sum(abundance))
  dat_size_div <- dat_size_div %>% group_by(year, cl_long, ordre) %>%
                                   summarise(diversity = length(unique(codeqc))) %>%
                                   as.data.frame()

  serie <- dat_size_div %>% filter(year != max) %>%
                            group_by(cl_long) %>%
                            summarise(pds_serie = mean(diversity),
                                      sd = sd(diversity)) %>%
                            as.data.frame()
  dat_size_div <- left_join(dat_size_div, serie, by = c("cl_long"))
  dat_size_div <- dat_size_div %>% group_by(year, cl_long) %>%
                                   summarise(anom = ((mean(diversity)) - pds_serie) / sd) %>% distinct()

  # BODY CONDITION =============================================================
  spp <- c(13,90,91,150,187,320,438,444,447,461,478,700,716,745,792,814,889,890,892,893)
  ngsl <- left_join(set, carbio, by = c("nav", "rel", "trait"))
  ngsl <- ngsl %>% filter(annee %in% c(min:max) &
                          !(rel == 1 & nav == 10) &
                            rel != 19 &
                            typtrait == 1 &
                            resultat %in% c(1, 2) &
                            !is.na(longueur) &
                            !is.na(pds_tot) &
                            no_str %in% core &
                            espece %in% spp)

  ngsl <- left_join(ngsl, coeff, by = "espece")

  ngsl <- ngsl %>% select(annee, no_str, espece, longueur, pds_tot, intercept, pente) %>%
    mutate(we = (exp(intercept)*(longueur^pente)), index = pds_tot/we)

  # Remove outliers
  ngsl <- ngsl %>% group_by(espece) %>% mutate(mean = mean(index), sd = sd(index))
  ngsl <- filter(ngsl, index < (mean+(2*sd)) & index > (mean-(2*sd)))

  dat_cond <- ngsl %>% group_by(annee, espece) %>% summarise(ind = mean(index))

  serie <- dat_cond %>% filter(annee != max) %>% # exclude last year of the series
                             group_by(espece) %>%
                             summarise(pds_serie = mean(ind), sd = sd(ind)) %>%
                             as.data.frame()
  dat_condition <- left_join(dat_cond, serie, by = c("espece"))
  dat_condition <- dat_condition %>% group_by(annee, espece) %>%
                                     summarise(anom = (ind - pds_serie) / sd, mean = ind) %>% distinct()

  # Calculate condition index for ALL SPECIES COMBINED
  serie <- dat_cond %>% filter(annee != max) %>% # exclude last year of the series
                             ungroup() %>%
                             summarise(pds_serie = mean(ind), sd = sd(ind)) %>%
                             as.data.frame()
  tot <- ngsl %>% group_by(annee, espece) %>% summarise(ind = mean(index))
  tot <- tot %>% group_by(annee) %>% reframe(ind = mean(ind)) %>% as.data.frame()
  tot$pds_serie <- serie$pds_serie
  tot$sd <- serie$sd
  tot <- tot %>% group_by(annee) %>% reframe(anom = (ind - pds_serie) / sd, mean = ind) %>% distinct()
  tot$espece <- 9999

  dat_condition <- bind_rows(dat_condition, tot)

  # Add taxonomic names
  dat_condition <- left_join(dat_condition, taxa %>% select(espece, nom_commun_en, nom_commun_fr, nom_scient), by = "espece")
  dat_condition[dat_condition$espece == 9999,]$nom_commun_fr <- "Toutes les espèces"
  dat_condition[dat_condition$espece == 9999,]$nom_commun_en <- "All species"


  # OCCUPATION/ABUNDANCE =======================================================
  dat_occ_abund <- dat %>% filter(PID == 25)
  names(dat_occ_abund) <- recode(names(dat_occ_abund), "pds_mean" = "a")
  stratum <- stratum %>% filter(no_str %in% core) %>% mutate(a_t0 = sum(surfkm91), w = surfkm91/a_t0)

  # Calculate abundance
  ## Data filering
  capt <- left_join(catch, set %>% select(nav,rel,trait,typtrait,resultat,dist_vit), by = c("nav", "rel", "trait"))
  capt <- capt %>% filter(!(rel == 1 & nav == 10) &
                            rel != 19 &
                            typtrait == 1 &
                            resultat %in% c(1, 2) &
                            !is.na(dist_vit) &
                            no_str %in% core)

  ## Select species ##
  spp <- c(13,90,91,150,187,320,438,447,461,478,792,814,889,890,892,893,8057,8111,8112,8135)
  capt <- capt %>% filter(espece %in% spp)

  ## Calculate abundance for each species
  a <- 16.71  * 0.75 * 1852 / 10^6
  abun <- capt %>% mutate(surf_ech = 16.71 * (dist_vit * 1852) / 10^6,
                          pds_capt_cor = pds_capt_cor_ca * a / surf_ech) %>%
    group_by(annee, espece, no_str) %>%
    reframe(pds_str = mean(pds_capt_cor))
  abun <- left_join(abun, stratum, by = "no_str")

  abun_str <- abun %>% group_by(annee, espece) %>% mutate(a_t0 = sum(surfkm91),
                                                          w = surfkm91/a_t0,
                                                          pds_prop = pds_str*w)

  abund <- abun_str %>% group_by(annee, espece) %>% reframe(a = sum(pds_prop))


  # Calculate occupancy
  ## Data filtering
  set <- set %>% filter(annee >= 2006 &
                        !(rel == 1 & nav == 10) &
                          rel != 19 &
                          typtrait == 1 &
                          resultat %in% c(1, 2) &
                          !is.na(dist_vit) &
                          no_str %in% core)


  ngsl <- left_join(set, catch %>% select(nav, rel, trait, espece), by = c("nav", "rel", "trait"))

  ## Select species ##
  spp <- c(13,90,91,150,187,320,438,447,461,478,792,814,889,890,892,893,8057,8111,8112,8135)
  ngsl <- ngsl %>% filter(espece %in% spp)

  ## Calculate occupancy for each species
  df_with_zeros <- ngsl %>% select(annee, espece, no_str) %>%
    group_by(annee, espece, no_str) %>%
    reframe(n = n()) %>% distinct() %>% ungroup() %>%
    complete(annee, espece, no_str, fill = list(n = 0))

  df_with_zeros$occ <- ifelse(df_with_zeros$n > 0, 1, 0)
  df <- left_join(df_with_zeros, stratum, by = "no_str")
  df <- df %>% mutate(occ_prop = occ*w) %>% group_by(annee, espece) %>% reframe(o = sum(occ_prop))

  ## Merge occupancy with abundance values
  dat_occ_abund <- left_join(abund, df, by = c("annee", "espece"))

  ## Calculate indicator
  unique(dat_occ_abund$espece)
  result <- data.frame()
  year <- c(min:max)
  for (i in year){
    yr <- dat_occ_abund %>% filter(annee == i) %>%
      group_by(annee, espece) %>%
      reframe(a= a, o = (o)*100) %>% distinct()
    lm.oa <- lm(o~log(a), data = yr)
    OA.rsquare <- summary(lm.oa)$r.squared
    OA.pente <- lm.oa[["coefficients"]][[2]]
    OA.intercept <- lm.oa[["coefficients"]][[1]]
    OA.pvalue <- summary(lm.oa)$coefficients[,"Pr(>|t|)"][[2]]
    annee <- i
    j <- data.frame(annee, OA.pente)
    result <- bind_rows(result, j)
  }

  # Fit log-linear function to O-A slopes
  result$annee <- as.numeric(result$annee)
  a <- result %>% filter(annee %in% c(min:max))
  lm <- lm(OA.pente~annee, data = a)
  x <- c(min:max)
  y <- predict.lm(lm)
  mod <- data.frame(x, y)
  names(mod) <- c("annee", "pente")

  dat_hab1 <- merge(result, mod, by = "annee")


  yr <- dat_occ_abund %>% group_by(annee, espece) %>%
    reframe(a= a, o = (o)*100) %>% distinct() %>% as.data.frame()

  # Add code for each species
  yr$code <- NA
  unique(yr$espece)
  yr[yr$espece == 13,]$code <- "MYLI"
  yr[yr$espece == 90,]$code <- "AMRA"
  yr[yr$espece == 91,]$code <- "MASE"
  yr[yr$espece == 150,]$code <- "CLHA"
  yr[yr$espece == 187,]$code <- "MAVI"
  yr[yr$espece == 320,]$code <- "ARRI"
  yr[yr$espece == 438,]$code <- "GAMO"
  yr[yr$espece == 447,]$code <- "URTE"
  yr[yr$espece == 461,]$code <- "ENCI"
  yr[yr$espece == 478,]$code <- "NEBA"
  yr[yr$espece == 792,]$code <- "SEBA"
  yr[yr$espece == 814,]$code <- "TRMU"
  yr[yr$espece == 889,]$code <- "HIPL"
  yr[yr$espece == 890,]$code <- "GLCY"
  yr[yr$espece == 892,]$code <- "REHI"
  yr[yr$espece == 893,]$code <- "HIHI"
  yr[yr$espece == 8057,]$code <- "PAMU"
  yr[yr$espece == 8111,]$code <- "PABO"
  yr[yr$espece == 8112,]$code <- "PAMO"
  yr[yr$espece == 8135,]$code <- "PONO"


  annee <- unique(yr$annee)
  OA <- data.frame()
  for (i in annee){
    rel <- yr %>% filter(annee == i)
    lm <- lm(o~log(a), data = rel)
    x <- rel$a
    y <- predict.lm(lm)
    mod <- data.frame(x, y)
    names(mod) <- c("a.yr", "o.yr")
    mod$annee <- i
    OA <- bind_rows(OA, mod)
  }

  dat_hab2_yr <- left_join(yr, taxa %>% select(espece, nom_commun_en, nom_commun_fr, nom_scient), by = "espece")
  dat_hab2_oa <- as.data.frame(OA)


# SAVE FILES ===================================================================
  # Overwrite?
  file_stems <- c("dat_productivity", "dat_stability", "dat_climate_guild", "dat_climate_cti",
                  "dat_flux_guild1", "dat_flux_guild2", "dat_flux_guild3", "dat_size_slope",
                  "dat_size_abund", "dat_size_div", "dat_hab1", "dat_hab2_yr", "dat_hab2_oa", "dat_condition")
  paths <- file.path(repository, paste0(file_stems, ".csv"))
  exists_mask <- file.exists(paths)
  if (any(exists_mask) && !isTRUE(overwrite)) {
    stop(
      "Fichier(s) déjà existant(s): ",
      paste(basename(paths[exists_mask]), collapse = ", "),
      ". Utilisez `overwrite = TRUE` pour écraser.",
      call. = FALSE
    )
  }

  if (any(exists_mask) & isTRUE(overwrite)) {
      message("Les fichiers ont été supprimés.")
      invisible(file.remove(paths[file.exists(paths)]))
  }

  # SAVE FILES =================================================================

  for (i in seq_along(file_stems)) {
    write.csv(get(file_stems[i]), file = paste0(repository, file_stems[i], ".csv"), row.names = FALSE)
  }

}
