#' Generate figures to update technical report indicators
#'
#' This function generate the figures published in Isabel et al. (2025).
#'
#'
#' @param repository Repository folder where files generated "generate_data" function are stored.
#' @param figures Repository folder where figures generated by the function are stored.
#' @param overwrite \code{TRUE} to overwrite existing files.
#'
#' @return (invisible) Figures created and stored.
#'
#' @examples
#' # example code
#' generate_figures(repository = "data/", figures = "fig/", overwrite = TRUE)
#'
#' @import ggplot2
#' @export
generate_figures <- function(
    repository,
    figures,
    overwrite = FALSE
) {

  # Create figures repository if it doesn't exist
  if (!dir.exists(figures)) {
    dir.create(figures, recursive = TRUE, showWarnings = FALSE)
    message("The figures repository was created.")
  }

  # Overwrite?
  file_stems <- c("graph_prod_fish", "graph_prod_inv", "graph_stability", "graph_climate_guild",
                  "graph_climate_cti", "graph_flux_biomass", "graph_flux_recent", "graph_flux_rate",
                  "graph_size_slope", "graph_size_abund", "graph_size_rich", "graph_condition",
                  "graph_hab_slope", "graph_hab_sp")
  paths <- file.path(repository, paste0(file_stems, ".png"))
  exists_mask <- file.exists(paths)
  if (any(exists_mask) && !isTRUE(overwrite)) {
    stop(
      "Figure(s) déjà existante(s): ",
      paste(basename(paths[exists_mask]), collapse = ", "),
      ". Utilisez `overwrite = TRUE` pour écraser.",
      call. = FALSE
    )
  }

  if (any(exists_mask) & isTRUE(overwrite)) {
    message("Les fichiers ont été supprimés.")
    invisible(file.remove(paths[file.exists(paths)]))
  }

  # LOAD DATA ==================================================================
  files <- list.files(path = repository, pattern = "\\.csv$", full.names = TRUE)
  for (f in files) {
    df_name <- tools::file_path_sans_ext(basename(f))
    assign(df_name, read.csv(f), envir = .GlobalEnv)
  }

  # CREATE FIGURES =============================================================
  # Set ggplot theme
  theme_graph <- theme_bw()+
    theme(text = element_text(family = "sans"),axis.title.y =
            element_text(angle = 90),
          axis.text.x = element_text(size = 10, colour = "black"),
          axis.text.y = element_text(size = 10, colour = "black"),
          plot.title = element_text(hjust = 0.5),
          legend.text = element_text(size = 8),
          legend.background = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(linewidth = 0.5),
          axis.line = element_line(linewidth = 0.5, colour = "black", linetype=1))
  theme_set(theme_graph)

  ######################################################################################################################
  # Set time series min and max
  min <- min(dat_productivity$annee)
  max <- max(dat_productivity$annee)

  ## Productivity ##
  # Anomalies for fishes
  fish <- c("Autres poissons", "Sébastes")

  dat_graph <- dat_productivity %>% filter(gr %in% fish, PID %in% c(1, 2)) %>% as.data.frame()
  graph1 <- ggplot(dat_graph, aes(x = annee)) +
    geom_bar(aes(y = anom, fill = gr), stat = "identity", position = "stack", colour = "black") +
    geom_hline(yintercept = 0.5, linetype = "dashed") +
    geom_hline(yintercept = -0.5, linetype = "dashed") +
    scale_fill_manual(values = c("Autres poissons" = "grey60", "Sébastes" = "red")) +
    scale_x_discrete(expand = c(0)) +
    labs(x = "", y = "Anomalie") +
    theme(legend.position = "none",
          legend.title = element_blank(),
          axis.text.x = element_blank(),
          plot.margin = unit(c(0, 0, 0, 0), "cm")) +
    facet_wrap(~PID, labeller = labeller(PID = c("1" = "Nord-ouest du golfe", "2" = "Nord-est du golfe")))

  dat_graph$anom <- ifelse(dat_graph$anom > -0.5 & dat_graph$anom < 0.5, 0, dat_graph$anom)
  graph2 <- ggplot(dat_graph, aes(x = annee, y = gr, fill = anom))+
    geom_tile(colour = "black", linewidth = 0.2) +
    geom_text(aes(label = round(mean, 2)), color = "black", size = 1.5) +
    scale_fill_gradient2(low="blue", mid="white", high = "red", limits = c(-3, 3), oob = scales::squish, breaks = c(-3,-2,-1,-0.5,0,0.5,1,2,3),
                         labels = c("< -3", "-2", "-1", "< -0.5", "0", "> 0.5", "1", "2", ">3"), midpoint = 0, guide = "legend") +
    scale_x_continuous(expand = c(0), breaks = round(seq(min, max, by = 1),0)) +
    scale_y_discrete(expand = c(0)) +
    labs(x = "Année", y = "") +
    theme(axis.text.x = element_text(hjust = 1, vjust = 0.5, angle = 90),
          legend.position = "none",
          plot.margin = unit(c(0, 0, 0, 0), "cm"),
          strip.text.x = element_blank()) +
    facet_wrap(~PID, labeller = labeller(PID = c("1" = "Nord-ouest du golfe", "2" = "Nord-est du golfe")))

  graph3 <- cowplot::plot_grid(graph1, graph2, ncol = 1, align = "v", axis = "top", rel_heights = c(3,1))

  dat_graph <- dat_productivity %>% filter(gr %in% fish & PID %in% c(3, 25)) %>% as.data.frame()
  graph4 <- ggplot(dat_graph, aes(x = annee)) +
    geom_bar(aes(y = anom, fill = gr), stat = "identity", position = "stack", colour = "black") +
    geom_hline(yintercept = 0.5, linetype = "dashed") +
    geom_hline(yintercept = -0.5, linetype = "dashed") +
    scale_fill_manual(values=c("Autres poissons"="grey60", "Sébastes"="red")) +
    scale_x_discrete(expand = c(0))+
    labs(x = "", y = "Anomalie") +
    theme(legend.position = "none",
          legend.title = element_blank(),
          axis.text.x = element_blank(),
          plot.margin = unit(c(0, 0, 0, 0), "cm")) +
    facet_wrap(~PID, labeller = labeller(PID = c("3" = "Centre du golfe", "25" = "nGSL")))

  dat_graph$anom <- ifelse(dat_graph$anom > -0.5 & dat_graph$anom < 0.5, 0, dat_graph$anom)
  graph5 <- ggplot(dat_graph, aes(x = annee, y = gr, fill = anom))+
    geom_tile(colour = "black", linewidth = 0.2) +
    geom_text(aes(label = round(mean, 2)), color = "black", size = 1.5) +
    scale_fill_gradient2(low="blue", mid="white", high = "red", limits = c(-3, 3), oob = scales::squish, breaks = c(-3,-2,-1,-0.5,0,0.5,1,2,3),
                         labels = c("<-3", "-2", "-1", "<-0.5", "0", ">0.5", "1", "2", ">3"), midpoint = 0, guide = "legend") +
    scale_x_continuous(expand = c(0), breaks = round(seq(min, max, by = 1),0)) +
    scale_y_discrete(expand = c(0)) +
    labs(x = "Année", y = "") +
    theme(axis.text.x = element_text(hjust = 1, vjust = 0.5, angle = 90),
          legend.position = "none",
          plot.margin = unit(c(0, 0, 0, 0), "cm"),
          strip.text.x = element_blank()) +
    facet_wrap(~PID, labeller = labeller(PID = c("3" = "Centre du golfe", "25" = "nGSL")))

  graph6 <- cowplot::plot_grid(graph4, graph5, ncol = 1, align = "v", axis = "top", rel_heights = c(3,1))

  legend <- ggplot(dat_graph, aes(x = annee, y = gr, fill = anom)) +
    geom_tile(color = "black") +
    scale_fill_gradient2(low="blue", mid="white", high = "red", limits = c(-3, 3), oob = scales::squish, breaks = c(-3,-2,-1,-0.5,0,0.5,1,2,3),
                         labels = c("<-3", "-2", "-1", "<-0.5", "0", ">0.5", "1", "2", ">3"), midpoint = 0, guide = "legend") +
    guides(fill = guide_legend(label.position = "bottom", title.position = "top", nrow = 1)) +
    theme(legend.key.spacing.x = unit(0, 'cm'),
          legend.position = "bottom",
          legend.title = element_blank(),
          plot.margin = unit(c(0, 0, 0, 0), "cm")) +
    facet_wrap(~PID, labeller = labeller(PID = c("3" = "Centre du golfe", "25" = "nGSL")))
  leg <- cowplot::get_legend(legend + theme(legend.background = element_rect(fill = "white", color = "black")))

  graph_prod_fish <- cowplot::plot_grid(graph3, graph6, leg, ncol = 1, nrow = 3, rel_heights = c(1,1,0.5))
  ggsave(filename = paste0(figures, "graph_prod_fish.png"), plot = graph_prod_fish, width = 10, height = 10, dpi = 600)

  # Anomalies for invertebrates
  dat_productivity$pos <- NA
  dat_productivity[dat_productivity$gr == "Crevette nordique", ]$pos <- 1
  dat_productivity[dat_productivity$gr == "Autres invertébrés", ]$pos <- 2

  inv <- c("Crevette nordique", "Autres invertébrés")

  dat_graph <- dat_productivity %>% filter(gr %in% inv & PID %in% c(1, 2)) %>% as.data.frame()
  dat_graph$gr <- reorder(dat_graph$gr, dat_graph$pos, decreasing = TRUE)
  graph1 <- ggplot(dat_graph, aes(x = annee)) +
    geom_bar(aes(y = anom, fill = gr), stat = "identity", position = "stack", colour = "black") +
    geom_hline(yintercept = 0.5, linetype = "dashed") +
    geom_hline(yintercept = -0.5, linetype = "dashed") +
    scale_fill_manual(values = c("Autres invertébrés" = "grey60", "Crevette nordique" = "red")) +
    scale_x_discrete(expand = c(0)) +
    labs(x = "", y = "Anomalie") +
    theme(legend.position = "none",
          legend.title = element_blank(),
          axis.text.x = element_blank(),
          plot.margin = unit(c(0, 0, 0, 0), "cm")) +
    facet_wrap(~PID, labeller = labeller(PID = c("1" = "Nord-ouest du golfe", "2" = "Nord-est du golfe")))

  dat_graph$anom <- ifelse(dat_graph$anom > -0.5 & dat_graph$anom < 0.5, 0, dat_graph$anom)
  graph2 <- ggplot(dat_graph, aes(x = annee, y = gr, fill = anom))+
    geom_tile(colour = "black", linewidth = 0.2) +
    geom_text(aes(label = round(mean, 2)), color = "black", size = 1.5) +
    scale_fill_gradient2(low="blue", mid="white", high = "red", limits = c(-3, 3), oob = scales::squish, breaks = c(-3,-2,-1,-0.5,0,0.5,1,2,3),
                         labels = c("< -3", "-2", "-1", "< -0.5", "0", "> 0.5", "1", "2", ">3"), midpoint = 0, guide = "legend") +
    scale_x_continuous(expand = c(0), breaks = round(seq(min, max, by = 1),0)) +
    scale_y_discrete(expand = c(0)) +
    labs(x = "Année", y = "") +
    theme(axis.text.x = element_text(hjust = 1, vjust = 0.5, angle = 90),
          legend.position = "none",
          plot.margin = unit(c(0, 0, 0, 0), "cm"),
          strip.text.x = element_blank()) +
    facet_wrap(~PID, labeller = labeller(PID = c("1" = "Nord-ouest du golfe", "2" = "Nord-est du golfe")))

  graph3 <- cowplot::plot_grid(graph1, graph2, ncol = 1, align = "v", axis = "top", rel_heights = c(3,1))

  dat_graph <- dat_productivity %>% filter(gr %in% fish & PID %in% c(3, 25)) %>% as.data.frame()
  graph4 <- ggplot(dat_graph, aes(x = annee)) +
    geom_bar(aes(y = anom, fill = gr), stat = "identity", position = "stack", colour = "black") +
    geom_hline(yintercept = 0.5, linetype = "dashed") +
    geom_hline(yintercept = -0.5, linetype = "dashed") +
    scale_fill_manual(values = c("Autres invertébrés" = "grey60", "Crevette nordique" = "red")) +
    scale_x_discrete(expand = c(0))+
    labs(x = "", y = "Anomalie") +
    theme(legend.position = "none",
          legend.title = element_blank(),
          axis.text.x = element_blank(),
          plot.margin = unit(c(0, 0, 0, 0), "cm")) +
    facet_wrap(~PID, labeller = labeller(PID = c("3" = "Centre du golfe", "25" = "nGSL")))

  dat_graph$anom <- ifelse(dat_graph$anom > -0.5 & dat_graph$anom < 0.5, 0, dat_graph$anom)
  graph5 <- ggplot(dat_graph, aes(x = annee, y = gr, fill = anom))+
    geom_tile(colour = "black", linewidth = 0.2) +
    geom_text(aes(label = round(mean, 2)), color = "black", size = 1.5) +
    scale_fill_gradient2(low="blue", mid="white", high = "red", limits = c(-3, 3), oob = scales::squish, breaks = c(-3,-2,-1,-0.5,0,0.5,1,2,3),
                         labels = c("<-3", "-2", "-1", "<-0.5", "0", ">0.5", "1", "2", ">3"), midpoint = 0, guide = "legend") +
    scale_x_continuous(expand = c(0), breaks = round(seq(min, max, by = 1),0)) +
    scale_y_discrete(expand = c(0)) +
    labs(x = "Année", y = "") +
    theme(axis.text.x = element_text(hjust = 1, vjust = 0.5, angle = 90),
          legend.position = "none",
          plot.margin = unit(c(0, 0, 0, 0), "cm"),
          strip.text.x = element_blank()) +
    facet_wrap(~PID, labeller = labeller(PID = c("3" = "Centre du golfe", "25" = "nGSL")))

  graph6 <- cowplot::plot_grid(graph4, graph5, ncol = 1, align = "v", axis = "top", rel_heights = c(3,1))

  legend <- ggplot(dat_graph, aes(x = annee, y = gr, fill = anom)) +
    geom_tile(color = "black") +
    scale_fill_gradient2(low="blue", mid="white", high = "red", limits = c(-3, 3), oob = scales::squish, breaks = c(-3,-2,-1,-0.5,0,0.5,1,2,3),
                         labels = c("<-3", "-2", "-1", "<-0.5", "0", ">0.5", "1", "2", ">3"), midpoint = 0, guide = "legend") +
    guides(fill = guide_legend(label.position = "bottom", title.position = "top", nrow = 1)) +
    theme(legend.key.spacing.x = unit(0, 'cm'),
          legend.position = "bottom",
          legend.title = element_blank(),
          plot.margin = unit(c(0, 0, 0, 0), "cm")) +
    facet_wrap(~PID, labeller = labeller(PID = c("3" = "Centre du golfe", "25" = "nGSL")))
  leg <- cowplot::get_legend(legend + theme(legend.background = element_rect(fill = "white", color = "black")))

  graph_prod_inv <- cowplot::plot_grid(graph3, graph6, leg, ncol = 1, nrow = 3, rel_heights = c(1,1,0.5))
  ggsave(filename = paste0(figures, "graph_prod_inv.png"), plot = graph_prod_inv, width = 10, height = 10, dpi = 600)

  ## Stability ##
  graph_stability <- ggplot(dat_stability) +
    geom_line(aes(x = annee, y = cv_tot), group = 1, colour = "blue", linewidth = 1, na.rm = TRUE) +
    geom_line(aes(x = annee, y = cv_sans_seb), group = 1, colour = "grey30", linewidth = 0.2, na.rm = TRUE) +
    geom_point(aes(x = annee, y=cv_tot), colour = "blue", na.rm = TRUE) +
    geom_hline(aes(yintercept = mean(cv_tot, na.rm = TRUE)), colour = "blue", linetype = "dashed", linewidth = 1) +
    geom_hline(aes(yintercept = mean(cv_sans_seb, na.rm = TRUE)), colour = "grey30", linetype = "dashed", linewidth = 0.2) +
    scale_x_continuous(expand = c(0.01), breaks = round(seq(min, max, by = 1),0)) +
    labs(x = "Année", y = "1/CV") +
    theme(legend.title = element_blank(),
          legend.position = c(0.15, 0.2),
          axis.text.x = element_text(hjust = 1, vjust = 0.5, angle = 90))
  ggsave(filename = paste0(figures, "graph_stability.png"), plot = graph_stability, width = 8, height = 6, dpi = 600)


  ## Climate change ##
  # Thermal guilds
  dat_graph1 <- dat_climate_guild %>% filter(guild == "chaud")
  cols_h <- c("#FEE0D2", "#FCBBA1", "#FC9272", "#EF3B2C", "#CB181D", "#67000D")
  dat_graph1$pos <- NA
  dat_graph1[dat_graph1$nom_commun_fr == "Merlu argenté", ]$pos <- 1
  dat_graph1[dat_graph1$nom_commun_fr == "Grande argentine", ]$pos <- 2
  dat_graph1[dat_graph1$nom_commun_fr == "Encornet rouge nordique", ]$pos <- 3
  dat_graph1[dat_graph1$nom_commun_fr == "Crevette (P. norvegicus)", ]$pos <- 4
  dat_graph1[dat_graph1$nom_commun_fr == "Crevette (A. propinqvus)", ]$pos <- 5
  dat_graph1[dat_graph1$nom_commun_fr == "Aiguillat noir", ]$pos <- 6

  dat_graph1$nom_commun_fr <- reorder(dat_graph1$nom_commun_fr, dat_graph1$pos, decreasing = TRUE)
  graph1 <- ggplot(data=dat_graph1, aes(x = annee)) +
    geom_bar(aes(y = pds, fill = nom_commun_fr), stat = "identity", color = "black", position = "stack") +
    labs(x = "Année", y = "Anomalie") +
    scale_fill_manual(values=cols_h) +
    scale_x_continuous(expand = c(0.01), breaks = round(seq(min, max, by = 1),0)) +
    geom_hline(yintercept = 0, linewidth = 0.6) +
    guides(fill = guide_legend(nrow = 2, ncol = 3, byrow = T, reverse = T)) +
    theme(legend.title = element_blank(),
          legend.position = "bottom",
          axis.text.x = element_text(hjust = 1, vjust = 0.5, angle = 90, size = 10))

  dat_graph2 <- dat_climate_guild %>% filter(guild == "froid")
  cols_c <- c("#DEEBF7", "#9ECAE1", "#4292C6", "#2171B5", "#08519C", "#08306B")
  dat_graph2$pos <- NA
  dat_graph2[dat_graph2$nom_commun_fr == "Saïda franc", ]$pos <- 1
  dat_graph2[dat_graph2$nom_commun_fr == "Petite poule Terre-Neuve", ]$pos <- 2
  dat_graph2[dat_graph2$nom_commun_fr == "Lycode du Labrador", ]$pos <- 3
  dat_graph2[dat_graph2$nom_commun_fr == "Crevette verte", ]$pos <- 4
  dat_graph2[dat_graph2$nom_commun_fr == "Bouc du Groenland", ]$pos <- 5
  dat_graph2[dat_graph2$nom_commun_fr == "Bouc Arctique", ]$pos <- 6

  dat_graph2$nom_commun_fr <- reorder(dat_graph2$nom_commun_fr, dat_graph2$pos, decreasing = TRUE)
  graph2 <- ggplot(data=dat_graph2, aes(x = annee)) +
    geom_bar(aes(y = pds, fill = nom_commun_fr), stat = "identity", color = "black", position = "stack") +
    labs(x = "Année", y = "Anomalie") +
    scale_fill_manual(values=cols_c) +
    scale_x_continuous(expand = c(0.01), breaks = round(seq(min, max, by = 1),0)) +
    geom_hline(yintercept = 0, linewidth = 0.6) +
    guides(fill = guide_legend(nrow = 2, ncol = 3, byrow = T, reverse = T)) +
    theme(legend.title = element_blank(),
          legend.position = "bottom",
          axis.text.x = element_text(hjust = 1, vjust = 0.5, angle = 90, size = 10))

  graph_climate_guild <- cowplot::plot_grid(graph1, graph2, labels = "AUTO", ncol = 1)
  ggsave(filename = paste0(figures, "graph_climate_guild.png"), plot = graph_climate_guild, width = 8, height = 10, dpi = 600)

  # CTI
  dat_climate_cti$PID <- as.character(dat_climate_cti$PID)
  cols <- c("#D7191C", "#FDAE61", "#ABDDA9", "#2B83BA")
  graph_climate_cti <- ggplot() +
    geom_point(data = dat_climate_cti, aes(x = annee, y = cti, color = PID, group = PID)) +
    geom_line(data = dat_climate_cti, aes(x = annee, y = cti, color = PID, group = PID)) +
    scale_x_continuous(expand = c(0.01), breaks = round(seq(min, max, by = 1),0)) +
    scale_color_manual(values = cols, labels =  c("1" = "Nord-ouest du golfe",
                                                  "2" = "Nord-est du golfe",
                                                  "3" = "Centre du golfe",
                                                  "25" = "nGSL")) +
    labs(x = "Année", y = "ITC") +
    theme(legend.title = element_blank(),
          legend.position = "bottom",
          axis.text.x = element_text(hjust = 1, vjust = 0.5, angle = 90, size = 10))
  ggsave(filename = paste0(figures, "graph_climate_cti.png"), plot = graph_climate_cti, width = 8, height = 6, dpi = 600)

  ## Trophic guilds ##
  # Total biomass anomalies
  cols <- c("darkblue", "yellowgreen", "orange", "forestgreen", "mediumorchid1", "firebrick4", "red2", "lightblue3")
  dat_flux_guild1$pos <- NA
  dat_flux_guild1[dat_flux_guild1$guild == "PP", ]$pos <- 1
  dat_flux_guild1[dat_flux_guild1$guild == "PIP", ]$pos <- 2
  dat_flux_guild1[dat_flux_guild1$guild == "PILD", ]$pos <- 3
  dat_flux_guild1[dat_flux_guild1$guild == "PB", ]$pos <- 4
  dat_flux_guild1[dat_flux_guild1$guild == "MM", ]$pos <- 5
  dat_flux_guild1[dat_flux_guild1$guild == "MD", ]$pos <- 6
  dat_flux_guild1[dat_flux_guild1$guild == "IF", ]$pos <- 7
  dat_flux_guild1[dat_flux_guild1$guild == "IB", ]$pos <- 8

  dat_flux_guild1$name <- reorder(dat_flux_guild1$name, dat_flux_guild1$pos, decreasing = TRUE)
  graph_flux_biomass <- ggplot(dat_flux_guild1, aes(x = annee, y = anom, fill = nom)) +
    geom_bar(stat = "identity", color = "black", linewidth = 0.2) +
    geom_hline(yintercept = 0, linewidth = 0.6) +
    scale_fill_manual(values = cols) +
    scale_x_continuous(expand = c(0.01), breaks = round(seq(min, max, by = 1),0)) +
    labs(x = "Année", y = "Anomalie") +
    guides(fill = guide_legend(nrow = 3, ncol = 3, byrow = T, reverse = T)) +
    theme(legend.position = "bottom",
          legend.title = element_blank(),
          legend.text = element_text(size = 8),
          axis.text.x = element_text(hjust = 1, vjust = 0.5, angle = 90)) +
    facet_wrap(~PID, labeller = labeller(PID =
                                           c("1" = "Nord-ouest du golfe",
                                             "2" = "Nord-est du golfe",
                                             "3" = "Centre du golfe",
                                             "25" = "nGSL")), nrow = 2, ncol = 2)
  ggsave(filename = paste0(figures, "graph_flux_biomass.png"), plot = graph_flux_biomass, width = 10, height = 10, dpi = 600)

  # Recent changes
  graph_flux_recent <- ggplot(data=dat_flux_guild2) +
    geom_bar(aes(x = nom, y = val, fill = gr), stat = "identity") +
    coord_flip() +
    scale_fill_manual(values = c("grey60", "red"), labels = c("Autres espèces", "Sébastes")) +
    labs(x = "", y = "Pourcentage", fill = NULL) +
    theme(axis.text.y = element_text(size = 8),
          legend.position = "bottom",
          panel.grid.major = element_line(color = "grey80"),
          panel.grid.minor = element_line(color = "grey80")) +
    facet_wrap(~PID, labeller = labeller(PID =
                                           c("1" = "Nord-ouest du golfe",
                                             "2" = "Nord-est du golfe",
                                             "3" = "Centre du golfe",
                                             "25" = "nGSL")), nrow = 2, ncol = 2)
  ggsave(filename = paste0(figures, "graph_flux_recent.png"), plot = graph_flux_recent, width = 10, height = 8, dpi = 600)

  # Trophic guild rate
  graph_flux_rate <- ggplot(dat_flux_guild3, aes(x = annee, y = pds_tot, fill = nom)) +
    geom_area(position = "stack", color = "black") +
    scale_fill_manual(values = cols) +
    scale_x_continuous(expand = c(0.01), breaks = round(seq(min, max, by = 1),0)) +
    labs(x = "Année", y = "Poids moyen (kg/trait)") +
    guides(fill = guide_legend(nrow = 3, ncol = 3, byrow = T, reverse = T)) +
    theme(axis.text.x = element_text(hjust = 1, vjust = 0.5, angle = 90),
          legend.position = "bottom",
          legend.title = element_blank()) +
    facet_wrap(~PID, labeller = labeller(PID = c("1" = "Nord-ouest du golfe",
                                                 "2" = "Nord-est du golfe",
                                                 "3" = "Centre du golfe",
                                                 "25" = "nGSL")), nrow = 2, ncol = 2)
  ggsave(filename = paste0(figures, "graph_flux_rate.png"), plot = graph_flux_rate, width = 10, height = 10, dpi = 600)

  ## Size structure ##
  # Slope of the size spectrum
  graph_size_slope <- ggplot(data = dat_size_slope, aes(x=year))+
    geom_point(aes(y = slope), size = 1.5, color = "blue")+
    geom_line(aes(y = gam_tot_slope), color = "blue", group = 1, linewidth = 1) +
    geom_line(aes(y = gam_no_seb_slope), color  = "grey30", group = 1, linewidth = 0.2) +
    scale_x_continuous(expand = c(0.01), breaks = round(seq(min, max, by = 1),0)) +
    labs(x = "Année", y = "Pente") +
    theme(legend.title = element_blank(),
          legend.position = c(0.2,0.9),
          axis.text.x = element_text(hjust = 1, vjust = 0.5, angle = 90))
  ggsave(filename = paste0(figures, "graph_size_slope.png"), plot = graph_size_slope, width = 8, height = 6, dpi = 600)

  # Abundance by size class
  dat_size_abund$pos <- NA
  dat_size_abund[dat_size_abund$cl_long == "[5-15[", ]$pos <- 1
  dat_size_abund[dat_size_abund$cl_long == "[15-25[", ]$pos <- 2
  dat_size_abund[dat_size_abund$cl_long == "[25-35[", ]$pos <- 3
  dat_size_abund[dat_size_abund$cl_long == "[35-45[", ]$pos <- 4
  dat_size_abund[dat_size_abund$cl_long == "[45-55[", ]$pos <- 5
  dat_size_abund[dat_size_abund$cl_long == "[55-65[", ]$pos <- 6
  dat_size_abund[dat_size_abund$cl_long == "[65-75[", ]$pos <- 7
  dat_size_abund[dat_size_abund$cl_long == "[75-85[", ]$pos <- 8
  dat_size_abund[dat_size_abund$cl_long == "[85-101[", ]$pos <- 9
  dat_size_abund$cl_long2 <- reorder(dat_size_abund$cl_long, dat_size_abund$pos)
  dat_size_abund$anom <- ifelse(dat_size_abund$anom > -0.5 & dat_size_abund$anom < 0.5, 0, dat_size_abund$anom)
  graph_size_abund <- ggplot(dat_size_abund, aes(x = year, y = cl_long2, fill = anom)) +
    geom_tile(color = "black", linewidth = 0.2) +
    scale_x_continuous(expand = c(0), breaks = round(seq(min, max, by = 1),0)) +
    scale_y_discrete(expand = c(0)) +
    scale_fill_gradient2(low="blue", mid="white", high = "red", limits = c(-3, 3), oob = scales::squish, breaks = c(-3,-2,-1,-0.5,0,0.5,1,2,3),
                         labels = c("<-3", "-2", "-1", "<-0.5", "0", ">0.5", "1", "2", ">3"), midpoint = 0, guide = "legend") +
    labs(x = "Année", y = "Classe de taille (cm)", fill = "Anomalie") +
    guides(fill = guide_legend(label.position = "bottom", title.position = "top", nrow = 1)) +
    theme(legend.key.spacing.x = unit(0, 'cm'),
          legend.position = "bottom",
          legend.title = element_blank(),
          axis.text.x = element_text(hjust = 1, vjust = 0.5, angle = 90))
  ggsave(filename = paste0(figures, "graph_size_abund.png"), plot = graph_size_abund, width = 10, height = 6, dpi = 600)

  # Species richness by size class
  dat_size_div$pos <- NA
  dat_size_div[dat_size_div$cl_long == "[5-15[", ]$pos <- 1
  dat_size_div[dat_size_div$cl_long == "[15-25[", ]$pos <- 2
  dat_size_div[dat_size_div$cl_long == "[25-35[", ]$pos <- 3
  dat_size_div[dat_size_div$cl_long == "[35-45[", ]$pos <- 4
  dat_size_div[dat_size_div$cl_long == "[45-55[", ]$pos <- 5
  dat_size_div[dat_size_div$cl_long == "[55-65[", ]$pos <- 6
  dat_size_div[dat_size_div$cl_long == "[65-75[", ]$pos <- 7
  dat_size_div[dat_size_div$cl_long == "[75-85[", ]$pos <- 8
  dat_size_div[dat_size_div$cl_long == "[85-101[", ]$pos <- 9
  dat_size_div$cl_long2 <- reorder(dat_size_div$cl_long, dat_size_div$pos)
  dat_size_div$anom <- ifelse(dat_size_div$anom > -0.5 & dat_size_div$anom < 0.5, 0, dat_size_div$anom)
  graph_size_rich <- ggplot(dat_size_div, aes(x = year, y = cl_long2, fill = anom)) +
    geom_tile(color = "black", linewidth = 0.2) +
    scale_x_continuous(expand = c(0), breaks = round(seq(min, max, by = 1),0)) +
    scale_y_discrete(expand = c(0)) +
    scale_fill_gradient2(low="blue", mid="white", high = "red", limits = c(-3, 3), oob = scales::squish, breaks = c(-3,-2,-1,-0.5,0,0.5,1,2,3),
                         labels = c("<-3", "-2", "-1", "<-0.5", "0", ">0.5", "1", "2", ">3"), midpoint = 0, guide = "legend") +
    labs(x = "Année", y = "Classe de taille (cm)", fill = "Anomalie") +
    guides(fill = guide_legend(label.position = "bottom", title.position = "top", nrow = 1)) +
    theme(legend.key.spacing.x = unit(0, 'cm'),
          legend.position = "bottom",
          legend.title = element_blank(),
          axis.text.x = element_text(hjust = 1, vjust = 0.5, angle = 90))
  ggsave(filename = paste0(figures, "graph_size_rich.png"), plot = graph_size_rich, width = 10, height = 6, dpi = 600)

  ## Condition ##
  dat_condition$nom <- reorder(dat_condition$nom_commun_fr, dat_condition$espece)
  dat_condition$anom <- ifelse(dat_condition$anom > -0.5 & dat_condition$anom < 0.5, 0, dat_condition$anom)
  graph_condition <- ggplot(dat_condition, aes(x = annee, y = nom, fill = anom)) +
    geom_tile(colour = "black", linewidth = 0.2) +
    scale_fill_gradient2(low="blue", mid="white", high = "red", limits = c(-3, 3), oob = scales::squish, breaks = c(-3,-2,-1,-0.5,0,0.5,1,2,3),
                         labels = c("<-3", "-2", "-1", "<-0.5", "0", ">0.5", "1", "2", ">3"), midpoint = 0, guide = "legend") +
    scale_x_continuous(expand = c(0), breaks = round(seq(min, max, by = 1),0)) +
    scale_y_discrete(expand = c(0)) +
    labs(x = "Année", y = "", fill = "Anomalie") +
    guides(fill = guide_legend(label.position = "bottom", title.position = "top", nrow = 1)) +
    theme(legend.key.spacing.x = unit(0, 'cm'),
          legend.position = "bottom",
          legend.title = element_blank(),
          axis.text.x = element_text(hjust = 1, vjust = 0.5, angle = 90))
  ggsave(filename = paste0(figures, "graph_condition.png"), plot = graph_condition, width = 10, height = 11, dpi = 600)

  ## Available habitat use ##
  graph_hab_slope <- ggplot(dat_hab1, aes(x = annee))+
    geom_point(aes(y = OA.pente), size = 1.5, color = "black")+
    geom_line(aes(y = pente), group = 1, linewidth = 0.6, color = "blue") +
    scale_x_continuous(expand = c(0.01), breaks = round(seq(min, max, by = 1),0)) +
    labs(x = "Année", y = "Pente") +
    theme(axis.text.x = element_text(hjust = 1, vjust = 0.5, angle = 90))
  ggsave(filename = paste0(figures, "graph_hab_slope.png"), plot = graph_hab_slope, width = 8, height = 6, dpi = 600)

  graph_hab_sp <- ggplot() +
    geom_point(data = dat_hab2_yr, aes(x = log(a), y = o, color = as.factor(annee)), size = 1) +
    geom_line(data = dat_hab2_oa, aes(x = log(a.yr), y = o.yr, color = as.factor(annee))) +
    geom_text(data = dat_hab2_yr, aes(x = log(a), y = o, label = code), size = 3, vjust = -0.5) +
    scale_color_viridis_d(breaks = c(min:max)) +
    scale_y_continuous(expand = c(0.01)) +
    labs(x = "log(Abondance)", y = "Occupation") +
    theme(legend.spacing.y = unit(5, "cm"),
          legend.title = element_blank())
  ggsave(filename = paste0(figures, "graph_hab_sp.png"), plot = graph_hab_sp, width = 10, height = 8, dpi = 600)



}
